app/urls.py
from django.urls import path
from .views import *

app_name='app'

urlpatterns=[
    path('',email_sending_func,name='email-send')
]

mail/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
import logging,requests
from django.shortcuts import render
from django.core.mail import get_connection,EmailMessage
from mail.settings import local as settings
from django.contrib import messages

# Create your views here.
def email_sending_func(request):
    if request.method == 'POST':
        try:
            # Sendgrid Email Sending Code
            email   = request.POST.get('email')
            connect = get_connection(host=settings.EMAIL_HOST,port=settings.EMAIL_PORT,username=settings.EMAIL_HOST_USER,password=settings.EMAIL_HOST_USER)
            sending = EmailMessage('Email Sent using Sendgrid Creds',body='Testing Sendgrid Email',from_email=settings.DEFAULT_FROM_EMAIL,to=[email],connection=connect)
            sending.content_subtype ='html'
            sending.send()
        except Exception as e:
            logging.error(e)
            try:
                # Mailgun Email Sending Code
                email = request.POST.get('email')
                response = requests.post("https://api.mailgun.net/v3/sandbox2affc1eb8d1c4b6b9104561f4e6daad6.mailgun.org/messages",auth = ("api", "ec49e59cec09a66c080326d28c52ed0d-c76388c3-a72d99e4"),
                    data = {
                      "from"    : "useremailmumbai@gmail.com",
                      "to"      : [f"{email}", "sandbox2affc1eb8d1c4b6b9104561f4e6daad6.mailgun.org"],
                      "subject" : "Email Send using Mailgun Creds",
                      "text"    : "Testing Mail Code Bravo !!!"})
                print(response)
                print('Email Send')
                messages.success('Email Send Successfully')
                return render(request, 'index.html')
            except Exception as e:
                logging.error(e)
    else:
        return render(request,'index.html')

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Sending Code</title>
    <style>
        .contact-form-wrapper {
              margin:50px auto;
              width: 600px;
              .title {
                margin-bottom:30px;
               }
              h1 {
                 font-size:18px;
                text-transform: uppercase;
                font-weight:bold;
              }
              p {
                font-size:14px;
                color: #777;
              }
            }
            .contact-form {
              input {
                border-radius:0;
                height:50px;
                font-size:12px;
                color:#999;
              }
              textarea {
                border-radius:0;
                font-size:12px;
                color:#999;
              }
              .submit-button {
                background: #00AEEF;
                color:#fff;
                font-size:12px;
                text-transform:uppercase;
                font-weight:bold;
                letter-spacing:1px;
              }
            }

    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
{% if messages %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            <p>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}


<div class="contact-form-wrapper">
    <div class="title text-center ">
        <h1>Mini Project Based on Email Service</h1>
        <p style="margin-top:31px;">
            Email Sending Service Platform
        </p>
    </div>

    <form action="{% url 'app:email-send' %}" id="contact-form" class="contact-form" method="POST" role="form">
        {% csrf_token %}
        <!--        <div class="form-group">-->
        <!--            <input type="text" placeholder="Your Name" class="form-control" name="name" id="name" required>-->
        <!--        </div>-->
        <div class="form-group text-center">
            <input type="email" placeholder="Your Email" class="form-control text-center" name="email" id="email" required>
        </div>

        <!--        <div class="form-group">-->
        <!--            <input type="text" placeholder="Subject" class="form-control" name="subject" id="subject" required>-->
        <!--        </div>-->

        <!--        <div class="form-group">-->
        <!--            <textarea rows="6" placeholder="Message" class="form-control" name="message" id="message" required></textarea>-->
        <!--        </div>-->
        <div id="submit" class="text-center">
            <input type="submit" id="contact-submit" class="btn btn-default submit-button" value="Send Message">
        </div>
    </form>
</div>
</body>
</html>